### ISSUE TITLE
Installing “magento2-tools@2.0.0” failed in windows8.0

### ISSUE THREAD

**Issue by pgsutariya** [nntoan/atom-magento2-tools#1]
Installing “magento2-tools@2.0.0” failed.Hide output…
Unable to download https://www.atom.io/api/packages/magento2-tools/versions/2.0.0/tarball: 404

This kind or error shows when install this tool in atom1.24.0 x64

**Comment by nntoan** [comment]
Yes, I notified to this problem few weeks ago. I was rebase and force update the commits but somehow Atom didn't update it. I will try to remove the current version from Atom side.

Thanks.

**Comment by VincentMarmiesse** [comment]
Hello,
I have the same issue, can I install it manually?

Thanks!

**Comment by arjus** [comment]
Same issue here on Mac OS X El Capitan. Looking forward for updates.
Thanks!

**Comment by DevBodin** [comment]
Same story for Windows 10.

**Comment by insanityNL** [comment]
Still got the same issue here. How can I fix this?

**Comment by nntoan** [comment]
Thanks for reporting. It's fixed now.
