### ISSUE TITLE
Installing “magento2-tools@2.0.0” failed in Win10 Pro

### ISSUE THREAD

**Issue by insanityNL** [nntoan/atom-magento2-tools#2]
Installing “magento2-tools@2.0.0” failed.Hide output…
Unable to download https://www.atom.io/api/packages/magento2-tools/versions/2.0.0/tarball: 404

This kind or error shows when install this tool in atom1.35.1 x64

**Comment by nntoan** [comment]
Thanks for reporting. It's fixed now.
